"""Generic Alembic revision script.

Revision ID: 13b649cac2a6
Revises: 48ea5f1d3e6c
Create Date: 2025-11-02 20:55:19.650134

"""
from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = '13b649cac2a6'
down_revision = '48ea5f1d3e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
