"""Generic Alembic revision script.

Revision ID: a37846da15c1
Revises: beca2239491a
Create Date: 2025-11-06 21:13:59.992612

"""
from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = 'a37846da15c1'
down_revision = 'beca2239491a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmt_offset_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmt_offset_minutes')
    # ### end Alembic commands ###
